- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Amit user exists"
    user:
      name: sunil
      state: present
  - name: "ensure Alex user exists"
    user:
      name: sunil
      state: present
      
